name: Docker imagiser

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - "**.json"
      - "**.html"
      - "Dockerfile"
      - ".Dockerignore"
      - "src/**"
      - "public/**"
  pull_request:
    branches:
      - 'main'
    paths:
      - "**.json"
      - "**.html"
      - "Dockerfile"
      - ".Dockerignore"
      - "src/**"
      - "public/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get commit message header
        id: get_commit_message
        run: |
          echo "COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B | head -n 1)" >> $GITHUB_ENV

      - name: BlockFluxCD
        if: env.COMMIT_MESSAGE_HEADER == 'Update from image update automation'
        uses: action-pack/cancel@v1

      - name: TimeTag
        run: echo "TIME_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.event.repository.name }}:build-${{ env.TIME_TAG }}
            ghcr.io/${{ github.event.repository.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
